name: Deploy to InfinityFree

on:
  push:
    branches: [ main ]   # change if your default branch is different
  workflow_dispatch:      # allow manual runs from the Actions tab

permissions:
  contents: read

concurrency:
  group: "ftp-deploy"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # If you build anything (e.g., npm run build), do it here before deploy.
      # - name: Build site
      #   run: |
      #     npm ci
      #     npm run build

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}        # e.g. ftpupload.net
          username: ${{ secrets.FTP_USERNAME }}    # e.g. epiz_12345678
          password: ${{ secrets.FTP_PASSWORD }}    # your InfinityFree FTP password
          protocol: ftps
          port: 21
          local-dir: ./                            # what to upload (repo root)
          server-dir: /htdocs/                     # InfinityFree web root
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/README.md
            **/.vscode/**
            **/.DS_Store
